version: "3"
services:
  bisim:
    image: beigemaps
    container_name: beigemaps
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
    environment:
      - MUJOCO_GL=egl
    volumes: 
      - ./src:/project/src
      - ./logdir:/project/logdir
      - ./storage:/project/storage