name: BeigeMapDBC
exp_mode: ???
overrides:
  model:
    encoder_mode: beigemap_dbc
    encoder_type: pixel_l2
    decoder_type: pixel_l2
  trainer:
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
sweeper:
  name: BeigeMapDBC
  num_runs: 1
  parameters:
    trainer:
      seed: {values: [2]}