name: Test
exp_mode: ???
overrides:
  model:
    encoder_mode: neural_ef_ksme
    encoder_softmax: False
  trainer:
    eval_freq: 99
    log_epoch_freq: 10
    init_steps: 10
    num_train_steps: 1000
    save_checkpoint_freq: 100
    terminal_display: rich
    replay_buffer:
      replay_buffer_capacity: 5000
sweeper:
  name: test_two
  num_runs: 3
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}